# This is a basic workflow to help you get started with Actions

name: Continuous Integration

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the '*' branch
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
    tags: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Setup
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install luarocks and busted
        run: |
          wget https://luarocks.org/releases/luarocks-3.7.0.tar.gz
          tar zxpf luarocks-3.7.0.tar.gz
          cd luarocks-3.7.0
          ./configure && make && sudo make install
          luarocks install busted
          cd ..

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout github branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        run: |
          luarocks make
          busted test/test.lua
